### ISSUE TITLE
Enable Prow CI for Service Catalog Tester

### ISSUE THREAD

**Issue by mszostok** [kyma-incubator/service-catalog-tester#2]
**Description**

Enable Prow CI for Service Catalog Tester.

**Reasons**

For now, there are not CI for this project, so we need to manually push new images and also execute the before-commit script which can be an error-prone

**Comment by jasiu001** [comment]
After consultation, I created image under `eu.gcr.io/kyma-project/incubator/` directory.

**Comment by adamwalach** [comment]
Its done: https://github.com/kyma-project/test-infra/issues/163
